Custom drp op
gastromatic/react-dates pull request #1
Opened 2019-09-11 15:24 UTC by mykhailoB8

2019-09-12 11:26 UTC, tofaelahmed requested changes

2019-09-12 11:26 UTC, tofaelahmed commented on src/components/CalendarDay.jsx
> +    background: '#FFF2F2',
Can you use values from theme like how its being used in other styles?

2019-09-12 11:26 UTC, tofaelahmed commented on src/components/CalendarMonth.jsx
> +      week.forEach((day) => {
Can you extract this logic into a function.

2019-09-12 11:26 UTC, tofaelahmed commented on src/components/CalendarMonth.jsx
> +          lastInvalidWeek = i;
It seems you can early break this loop?

2019-09-12 11:26 UTC, tofaelahmed commented on src/components/CalendarMonth.jsx
> +    const activePeriod = `Optimierungszeitraum ${currentMonth.month() + 1} (KW ${firstWeekIndex} - KW ${lastWeekIndex})`;
hardocded labels (eg: `Optimierungszeitraum`) should not be used

2019-09-12 11:26 UTC, tofaelahmed commented on src/components/CalendarMonth.jsx
> +                  <td style={{ padding: '5px 5px 5px 10px', textAlign: 'left' }}>
to be consistent with the existing coding style please use css in js style

2019-09-17 08:58 UTC, tofaelahmed commented on src/components/DayPickerRangeController.jsx
> +          day.clone().startOf('isoWeek').month() > startDate.month()
you can clone once and reuse.

2019-09-17 08:58 UTC, tofaelahmed commented on src/components/DayPickerRangeController.jsx
> +          day.clone().startOf('isoWeek').month() > startDate.month()
same here

2019-09-17 11:12 UTC, mykhailoB8 commented on src/components/CalendarDay.jsx
> +    background: '#FFF2F2',
We are using theme in gastromatic-ui and overriding default values. In gastromatic-react-dates used default values.

2019-09-17 11:46 UTC, mykhailoB8 commented on src/components/CalendarMonth.jsx
> +          lastInvalidWeek = i;
No. I need to find last item, not first.

2019-09-17 13:20 UTC, mykhailoB8 commented on src/components/CalendarMonth.jsx
> +      week.forEach((day) => {
Done

2019-09-17 13:20 UTC, mykhailoB8 commented on src/components/CalendarMonth.jsx
> +    const activePeriod = `Optimierungszeitraum ${currentMonth.month() + 1} (KW ${firstWeekIndex} - KW ${lastWeekIndex})`;
Done

2019-09-17 13:56 UTC, mykhailoB8 commented on src/components/CalendarMonth.jsx
> +                  <td style={{ padding: '5px 5px 5px 10px', textAlign: 'left' }}>
Done

2019-09-17 14:00 UTC, mykhailoB8 commented on src/components/DayPickerRangeController.jsx
> +          day.clone().startOf('isoWeek').month() > startDate.month()
Done

2019-09-17 14:00 UTC, mykhailoB8 commented on src/components/DayPickerRangeController.jsx
> +          day.clone().startOf('isoWeek').month() > startDate.month()
Done

2019-10-10 08:43 UTC, dehrhard commented
deprecated

2019-10-10 08:43 UTC, closed without merging